### ISSUE TITLE
Setup script exited with error in isso setup command

### ISSUE THREAD

**Issue by fuzzmz** [avinassh/isso-openshift#1]
After pushing changes to the `production.cfg` isso fails to install with the following error:

`remote: error: Setup script exited with error in isso setup command: Invalid environment marker: python_version>="3.0"`

Full deployment log attached: [deployment.txt](https://github.com/avinassh/isso-openshift/files/175580/deployment.txt)

**Comment by avinassh** [comment]
Please tell me the steps you followed to install.

**Comment by fuzzmz** [comment]
@avinassh, it's reproducible by installing both via rhc with `rhc create-app appname python-2.7 --from-code https://github.com/avinassh/isso-openshift.git` as well as via the openshift web interface + this repo as source code.

I've also tried upgrading pip (workaround mentioned in posativ/isso#232) but when manually running `python app.py server` it returns an import error:

``` python
Traceback (most recent call last):
  File "app.py", line 16, in <module>
    from isso.core import Config
ImportError: cannot import name Config
```

**Comment by avinassh** [comment]
Hey I confirm that this issue exists. I will fix this by weekend.

**Comment by fuzzmz** [comment]
Hey @avinassh, any updates on this? Or any guidance on where to start looking in order to fix this myself and submit a PR?

**Comment by avinassh** [comment]
Hey, I have been very busy so I couldn't work on it. I will try to do this by this weekend. 

If you want to work, then check how Isso is handling config files and how it runs. Basically this issue is happening cos Openshift installs latest available Isso since I haven't mentioned [specific version](https://github.com/avinassh/isso-openshift/blob/master/setup.py#L9) and something probably changed in newer versions. So that thing needs to be figured out.

Next, you mostly have to update the `production.cfg` of this repo with [latest changes](https://github.com/posativ/isso/blob/master/share/isso.conf) required by Isso.

If you are not able to figure out anything, then post here, I will be happy to help. However I will promise you that I will fix it before weekend. Thanks!

**Comment by avinassh** [comment]
@fuzzmz as promised, I have fixed the issue. Please check :) I will close this issue once you confirm.

For demo, I am running an instance here: http://isso-avinassh.rhcloud.com/info

**Comment by fuzzmz** [comment]
@avinassh, it now installs correctly though it doesn't seem to expose the `embed.min.js` file. For example http://isso-avinassh.rhcloud.com/js/embed.min.js return `404 file not found`.

**Comment by avinassh** [comment]
hey I have this issue since beginning and I couldn't solve it. However you can use `embed.min.js` from anywhere. 

Either you can host it somewhere or you can use this: http://avi.im/stuff/embed.min.js

let me know if you need any help regarding this.

**Comment by fuzzmz** [comment]
D'oh, don't know why I didn't think of that. Thanks @avinassh, you're a life saver!

**Comment by avinassh** [comment]
Glad to be of help! Cheers using Isso 🍻
